config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "books#index", as: :root
    resources :books
    resources :users
    resources :authors
    resources :publishers
    resources :categories
  end

  root "static_pages#show", act: "home"
  get "/pages/:act" => "static_pages#show"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: :destroy do
    resources :follow_users, only: [:create, :destroy]
  end
  resources :books, only: [:show] do
    resources :comments, only: [:create]
    resources :like_books, only: [:create, :destroy]
  end
  resources :authors, only: [:show] do
    resources :follow_authors, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :followed, as: :followed, class_name: Relationship.name
  has_many :follower, as: :follower, class_name: Relationship.name
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors, foreign_key: :book_id
  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories, foreign_key: :book_id
  has_many :users_like, through: :followed, source: :follower,
    source_type: User.name
  belongs_to :publisher
  validates :title, presence: true, length: {maximum: 250}
  validates :pages, presence: true, length: {maximum: 6},
    numericality: {only_integer: true}
  validates :price, presence: true, length: {maximum: 9},
    numericality: {only_integer: true}
  validates :quantity, presence: true, length: {maximum: 4},
    numericality: {only_integer: true}
  validates :publish_date, presence: true

  scope :search_data, -> data {joins("LEFT JOIN book_categories
    on books.id = book_categories.book_id").where "title LIKE
    '%#{data[:content]}%' AND category_id = #{data[:category]}"}

  class << self
    def search data
      self.search_data data
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::AdminController
  before_action :find_book, except: [:new, :index, :create]
  before_action :load_data, only: [:new, :edit, :index]

  def index
    @books = if params[:content]
      Book.search params
    else
      Book.all
    end.paginate page: params[:page], per_page: Settings.per_page
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "admin.book.update.success"
      redirect_to admin_books_path
    else
      @categories = Category.all
      render :edit
    end
  end

  def new
    @book = Book.new
  end

  def show
  end

  def create
    @book = Book.new book_params
    if @book.save
      params[:book][:author_ids].each do |author_id|
        @book.book_authors.create! author_id: author_id unless author_id.blank?
      end
      params[:book][:category_ids].each do |category_id|
        @book.book_categories.create! category_id: category_id unless category_id.blank?
      end
      redirect_to admin_root_path
    else
      load_data
      render :new
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t "admin.book.destroy.success"
    else
      flash[:danger] = t "adnin.book.destroy.danger"
    end
    redirect_to :back
  end

  private
  def find_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:danger] = t "books.error.book_not_found"
      redirect_to root_path
    end
  end

  def book_params
    params.require(:book).permit :title, :image, :pages, :price, :quantity,
      :publish_date, :publisher_id, :description, :status
  end

  def load_data
    @supports = Supports::NewBook.new
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show]

  def show
    @comment = @book.comments.new
    @comments = @book.comments
      .paginate page: params[:page], per_page: Settings.static_pages.per_page
    @user_relationship_book =
      if logged_in? && current_user.follower_books.include?(@book)
        current_user.follower.find_by followed_id: @book.id,
          followed_type: Book.name
      end
  end

  private
  def find_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:danger] = t "books.error.book_not_found"
      redirect_to root_path
    end
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td class="col-md-2"><%= link_to book.title, admin_book_path(book), target: "_new" %></td>
  <td class="col-md-1"><%= book.price %></td>
  <td class="col-md-1"><%= book.status %></td>
  <td class="col-md-1"><%= book.rate_point %></td>
  <td class="col-md-1"><%= book.view_count %></td>
  <td class="col-md-1"><%= book.quantity %></td>
  <td class="col-md-1"><%= book.pages %></td>
  <td class="col-md-1"><%= book.publish_date %></td>
  <td class="col-md-1"><%= l book.created_at, format: :default %></td>
  <td class="col-md-1"><%= l book.updated_at, format: :default %></td>
  <td class="col-md-1">
  <%= link_to t("admin.book.action.edit"), edit_admin_book_path(book),
    id: "open-contacts-dialog-btn", class: "btn btn-primary inbox-sf-add-btn tip"%>
  <br>
  <br>
  <%= link_to t("admin.book.action.delete"), admin_book_url(book),
    id: "open-contacts-dialog-btn", class: "btn btn-danger inbox-sf-add-btn tip",
    method: :delete, data: {confirm: t("admin.index.confirm")} %>
  </td>
</tr>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render "shared/error_messages", object: @book %>

  <%= f.label :categories %>
  <%= f.select :category_ids, @supports.categories.collect {|category|
    [category.name, category.id]}, {selected: @supports.categories.first},
      {multiple: true, class: "form-control"} %>

  <%= f.label :authors %>
  <%= f.select :author_ids, @supports.authors.collect {|author|
    [author.name, author.id]}, {selected: @supports.authors.first},
      {multiple: true, class: "form-control"} %>

  <%= f.label :publisher %>
  <%=  f.select :publisher_id, @supports.publishers.collect {|publisher|
    [publisher.name, publisher.id]}, {}, class: "form-control" %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.label :pages %>
  <%= f.number_field :pages, class: "form-control" %>

  <%= f.label :status %>
  <%= f.number_field :status, class: "form-control" %>

  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control" %>

  <%= f.label :quantity %>
  <%= f.number_field :quantity, class: "form-control" %>

  <%= f.label :publish_date %>
  <%= f.date_field :publish_date, class: "form-control datepicker" %>
  <br>
  <span class="image">
    <%= f.label :image %>
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/edit.html.erb
<% provide :title, t("admin.book.update.namesite") %>
<% provide :button_text, t("admin.book.save") %>
<h1><%= t "admin.book.update.namesite" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<div class="ltt-books-index-header">
  <h1 class="col-md-2"><%= t "admin.book.all" %></h1>
  <div class="row col-md-10">
    <div class="col-md-6 ltt-books-search">
      <%= form_tag admin_books_path, method: :get, remote: true do %>
        <%= select_tag :category,
          options_for_select(@supports.list_categories),
          class: "form-control books-search-select" %>
        <%= text_field_tag :content, "", placeholder: t("admin.search"),
          class: "form-control books-search-input", value: nil %>
        <%= submit_tag t("admin.search"), class: "btn btn-primary" %>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<div class="row">
<table class="table table-bordered table table-striped">
  <thead>
    <tr>
      <th class="col-md-2"><%= t "admin.book.title" %></th>
      <th class="col-md-1"><%= t "admin.book.price" %></th>
      <th class="col-md-1"><%= t "admin.book.status" %></th>
      <th class="col-md-1"><%= t "admin.book.rate_point" %></th>
      <th class="col-md-1"><%= t "admin.book.view_count" %></th>
      <th class="col-md-1"><%= t "admin.book.quantity" %></th>
      <th class="col-md-1"><%= t "admin.book.pages" %></th>
      <th class="col-md-1"><%= t "admin.book.publish_date" %></th>
      <th class="col-md-1"><%= t "admin.book.created_at" %></th>
      <th class="col-md-1"><%= t "admin.book.updated_at" %></th>
      <th class="col-md-1"><%= t "admin.book.action.title" %></th>
    </tr>
  </thead>
  <tbody class="ltt-books-content">
    <%= render @books %>
  </tbody>
</table>
<div class="ltt-users-navbar pull-right">
  <%= link_to t("admin.book.add_book"), new_admin_book_path, id: "open-contacts-dialog-btn",
    class: "btn btn-primary inbox-sf-add-btn tip" %>
</div>

app/views/admin/books/index.js.erb
$('.ltt-books-content').html('<%= j render @books %>');

app/views/admin/books/new.html.erb
<% provide :title, t("admin.book.namesite") %>
<% provide :button_text, t("admin.book.save") %>
<h1><%= t "admin.book.namesite" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/show.html.erb
<% provide :title, t("books.show.title") + @book.title %>
<div class="row book-detail">
  <div class="col-sm-12">
    <div class="col-sm-5 img">
      <%= image_tag @book.image, class: "img-book img-responsive" %>
    </div>
    <div class="col-sm-7">
      <h2><%= @book.title %></h2>
      <hr>
      <div class="row">
        <div class="col-sm-3"><%= t "books.show.price" %></div>
        <div class="col-sm-9"><%= @book.price %></div>
        <div class="col-sm-3"><%= t "books.author" %></div>
        <div class="col-sm-9">
          <% @book.authors.each do |author| %>
            <%= link_to author.name, "#" %>,
          <% end %>
        </div>
        <div class="col-sm-3"><%= t "books.publish_date" %></div>
        <div class="col-sm-9"><%= l @book.publish_date, format: :default %></div>
        <div class="col-sm-3"><%= t "books.show.quantity" %></div>
        <div class="col-sm-9"><%= @book.quantity %></div>
        <div class="col-sm-3"><%= t "books.show.pages" %></div>
        <div class="col-sm-9"><%= @book.pages %></div>
      </div>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="col-sm-5">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
          <%= link_to t("books.show.description"),
            "#description",
            "aria-controls": "description",
            "role": "tab",
            "data-toggle": "tab" %>
        </li>
        <li role="presentation">
          <%= link_to t("books.show.comments"),
            "#comments",
            "aria-controls": "comments",
            "role": "tab",
            "data-toggle": "tab" %>
        </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="description">
          <%= @book.description %>
        </div>
        <div role="tabpanel" class="tab-pane" id="comments"></div>
      </div>
    </div>
    <div class="col-sm-7">
      <h3><%= t "books.show.recommend_books" %></h3>
    </div>
  </div>
</div>