config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "books#index", as: :root
    resources :books
    resources :users
    resources :authors
    resources :publishers
    resources :categories
  end

  root "static_pages#show", act: "home"
  get "/pages/:act" => "static_pages#show"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: :destroy do
    resources :follow_users, only: [:create, :destroy]
  end
  resources :books, only: [:show] do
    resources :comments, only: [:create]
    resources :like_books, only: [:create, :destroy]
  end
  resources :authors, only: [:show] do
    resources :follow_authors, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
end

app/models/author.rb
class Author < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :followed, as: :followed, class_name: Relationship.name
  has_many :follower, as: :follower, class_name: Relationship.name
  has_many :follower_users, through: :followed, source: :follower,
    source_type: User.name, dependent: :destroy
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors, foreign_key: :author_id

  validates :name, presence: true, length: {maximum: 50}
  validates :date_of_birth, presence: true

  scope :search_data, ->data {where "name LIKE '%#{data[:value]}%'"}

  class << self
    def search data
      self.search_data data
    end

    def to_csv options = {}
      CSV.generate options do |csv|
        csv << column_names
        all.each do |author|
          csv << author.attributes.values_at(*column_names)
        end
      end
    end
  end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < Admin::AdminController
  before_action :find_author, except: [:new, :index, :create]

  def index
    @authors = if params[:value]
      Author.search params
    else
      Author.all
    end.paginate page: params[:page], per_page: Settings.per_page
    respond_to do |format|
      format.js
      format.html
      format.csv {send_data @authors.to_csv}
      format.xls {send_data @authors.to_csv(col_sep: "\t")}
    end
  end

  def show
    @books = @author.books
      .paginate page: params[:page], per_page: Settings.static_pages.per_page
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params
    if @author.save
      flash[:success] = t "admin.author.new.success"
      redirect_to admin_authors_path
    else
      flash[:danger] = t "admin.author.new.danger"
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update_attributes author_params
      flash[:success] = t "admin.author.update.success"
      redirect_to admin_authors_path
    else
      flash[:danger] = t "admin.author.update.danger"
      render :edit
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = t "admin.author.destroy.success"
    else
      flash[:danger] = t "adnin.author.destroy.danger"
    end
    redirect_to :back
  end

  private
  def find_author
    @author = Author.find_by id: params[:id]
    unless @author
      flash[:danger] = t "admin.book.error.not_found"
      redirect_to root_path
    end
  end

  def author_params
    params.require(:author).permit :name, :image, :date_of_birth, :body
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only: [:show]
  def show
    @books = @author.books
      .paginate page: params[:page], per_page: Settings.static_pages.per_page

      if logged_in? && current_user.follower_authors.include?(@author)
        @user_relationship_author =
          current_user.follower.find_by followed_id: @author.id,
          followed_type: Author.name
      end
  end

  private
  def find_author
    @author = Author.find_by id: params[:id]
    unless @author
      flash[:danger] = t "authors.error.author_not_found"
      redirect_to root_path
    end
  end
end

app/views/admin/authors/_author.html.erb
<tr>
  <td class="col-md-2"><%= link_to author.name, [:admin, author] %></td>
  <td class="col-md-2"><%= author.body %></td>
  <td class="col-md-1"><%= l author.date_of_birth, format: :default %></td>
  <td class="col-md-1">
    <%= link_to t("admin.author.action.edit"), edit_admin_author_path(author),
      id: "open-contacts-dialog-btn", class: "btn btn-primary inbox-sf-add-btn tip"%>
    <%= link_to t("admin.author.action.delete"), admin_author_url(author),
      id: "open-contacts-dialog-btn", class: "btn btn-danger inbox-sf-add-btn tip",
      method: :delete, data: {confirm: t("admin.index.confirm")} %>
  </td>
</tr>

app/views/admin/authors/_form.html.erb
<%= form_for [:admin, author] do |f| %>
  <%= render "shared/error_messages", object: @author %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :body %>
  <%= f.text_field :body, class: "form-control" %>

  <%= f.label :date_of_birth %>
  <%= f.date_field :date_of_birth, class: "form-control datepicker" %>
  <br>
  <span class="image">
    <%= f.label :image %>
    <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
  </span>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/authors/_navbar.html.erb
<p>
  <%= t "export.name" %>
  <%= link_to t("export.formats.csv"), admin_authors_path(format: "csv",
    value: params[:value], attribute: params[:attribute]) %> |
  <%= link_to t("export.formats.excel"), admin_authors_path(format: "xls",
    value: params[:value], attribute: params[:attribute]) %>
</p>

app/views/admin/authors/_stats.html.erb
<br>
<%= @author.follower_users.count %>
<%= t "authors.show.others" %>
<% if @user_relationship_author %>
  <%= form_for :user_relationship_author,
    url: author_follow_author_path(@author, @user_relationship_author),
    method: :delete, remote: true do |f| %>
    <%= hidden_field_tag :followed_id, @author.id %>
    <%= f.submit t("books.show.unlike"), class: "btn btn-primary" %>
  <% end %>
<% else %>
  <%= form_for :user_relationship_author,
    url: author_follow_authors_path(@author),
    method: :post, remote: true do |f| %>
    <%= hidden_field_tag :followed_id, @author.id %>
    <%= f.submit t("books.show.like"), class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/admin/authors/edit.html.erb
<% provide :title, t("admin.author.update.namesite") %>
<% provide :button_text, t("admin.author.save") %>
<h1><%= t "admin.book.update.namesite" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", author: @author %>
  </div>
</div>

app/views/admin/authors/index.html.erb
<div class="ltt-authors-index-header">
  <h1 class="col-md-2"><%= t "admin.author.all" %></h1>
  <div class="row col-md-10">
    <div class="col-md-6 ltt-authors-search">
      <%= form_tag admin_authors_path, method: :get, remote: true do %>
        <%= text_field_tag :value, "", placeholder: t("admin.search"),
          class: "form-control authors-search-input", value: nil %>
        <%= submit_tag t("admin.search"), class: "btn btn-primary" %>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<div class="row">
<table class="table table-bordered table table-striped">
  <thead>
    <tr>
      <th class="col-md-2"><%= t "admin.author.name" %></th>
      <th class="col-md-2"><%= t "admin.author.body" %></th>
      <th class="col-md-1"><%= t "admin.author.date_of_birth" %></th>
      <th class="col-md-1"><%= t "admin.author.action.title" %></th>
    </tr>
  </thead>
  <tbody class="ltt-authors-content">
    <%= render @authors %>
  </tbody>
</table>
<div class="ltt-authors-navbar pull-left">
  <%= render "navbar" %>
</div>
<div class="ltt-users-navbar pull-right">
  <%= link_to t("admin.author.add_author"), new_admin_author_path,
    id: "open-contacts-dialog-btn", class: "btn btn-primary inbox-sf-add-btn tip" %>
</div>

app/views/admin/authors/index.js.erb
$('.ltt-authors-content').html('<%= j render @authors %>');
$('.ltt-authors-navbar').html('<%= j render "navbar" %>');

app/views/admin/authors/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String"><%= t "admin.author.name" %></Data></Cell>
        <Cell><Data ss:Type="String"><%= t "admin.author.body" %></Data></Cell>
        <Cell><Data ss:Type="DateTime"><%= t "admin.author.date_of_birth" %>
          </Data></Cell>
      </Row>
    <% @authors.each do |author| %>
      <Row>
        <Cell><Data ss:Type="String"><%= author.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= author.body %></Data></Cell>
        <Cell><Data ss:Type="DateTime"><%= author.date_of_birth %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/authors/new.html.erb
<% provide :title, t("admin.author.namesite") %>
<% provide :button_text, t("admin.author.save") %>
<h1><%= t "admin.author.namesite" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", author: @author %>
  </div>
</div>

app/views/admin/authors/show.html.erb
<% provide :title, t("authors.show.title") + @author.name %>
<div class="row book-detail">
  <div class="col-sm-12">
    <div class="col-sm-3 img">
      <%= image_tag @author.image, class: "img-book img-responsive center-block" %>
    </div>
    <div class="col-sm-9">
      <h2>
        <%= @author.name %>
        <small id="stats">
          <%= render "stats" %>
        </small>
      </h2>
      <hr>
      <h5><%= l @author.date_of_birth, format: :default %></h5>
      <hr>
      <p><%= @author.body %></p>
    </div>
  </div>
  <div class="col-sm-12">
    <h3 class="text-right"><%= t "authors.show.list_books_of_author" %><%= @author.name %></h3>
    <hr>
    <div class="col-sm-9 col-sm-offset-3 list-items">
      <% @books.each do |book| %>
        <div class="col-sm-4 item">
          <%= link_to book do %>
            <div class="item-image">
              <%= image_tag "http://allstore-html.real-web.pro/img/catalog-gallery/2/1.jpg" %>
              <div class="item-action">
                <div class="item-box">
                  <p class="item-option text-center">
                  </p>
                  <button class="btn"><%= t "item.add_to_cart" %></button>
                </div>
              </div>
            </div>
          <% end %>
          <i class="item-info">i</i>
          <h4 class="text-center"><%= link_to book.title, "#", title: book.title %></h4>
          <h4 class="text-center"><%= book.price %> <%= t "item.currency" %></h4>
        </div>
      <% end %>
      <hr/>
      <%= will_paginate @books %>
    </div>
  </div>
</div>