config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "books#index", as: :root
    resources :books
    resources :users
    resources :authors
    resources :publishers
    resources :categories
  end

  root "static_pages#show", act: "home"
  get "/pages/:act" => "static_pages#show"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: :destroy do
    resources :follow_users, only: [:create, :destroy]
  end
  resources :books, only: [:show] do
    resources :comments, only: [:create]
    resources :like_books, only: [:create, :destroy]
  end
  resources :authors, only: [:show] do
    resources :follow_authors, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
end

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse ltt-header">
  <div class="container">
    <%= link_to t("site.name"), admin_root_path, id: "logo" %>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to t("admin.users"), admin_users_path %>
      </li>

      <li>
        <%= link_to t("admin.category"), admin_categories_path %>
      </li>

      <li>
        <%= link_to t("admin.book.name"), admin_books_path %>
      </li>

      <li>
        <%= link_to t("admin.author.title"), admin_authors_path %>
      </li>

      <li>
        <%= link_to t("admin.publisher.title"), admin_publishers_path %>
      </li>

      <li>
        <%= link_to t("admin.request"), "#" %>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.name %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to t("navbar.logout"), logout_path, method: :delete %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/admin/header" %>
    <div class="container ltt-body">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>