config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: "books#index", as: :root
    resources :books
    resources :users
    resources :authors
    resources :publishers
    resources :categories
  end

  root "static_pages#show", act: "home"
  get "/pages/:act" => "static_pages#show"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: :destroy do
    resources :follow_users, only: [:create, :destroy]
  end
  resources :books, only: [:show] do
    resources :comments, only: [:create]
    resources :like_books, only: [:create, :destroy]
  end
  resources :authors, only: [:show] do
    resources :follow_authors, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {maximum: 50}

  scope :search_data, ->data {where "name LIKE '%#{data[:value]}%'"}

  class << self
    def search data
      self.search_data data
    end

    def to_csv options = {}
      CSV.generate options do |csv|
        csv << column_names
        all.each do |publisher|
          csv << publisher.attributes.values_at(*column_names)
        end
      end
    end
  end
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < Admin::AdminController
  before_action :find_publisher, except: [:new, :index, :create]

  def index
    @publishers = if params[:value]
      Publisher.search params
    else
      Publisher.all
    end.paginate page: params[:page], per_page: Settings.per_page
    respond_to do |format|
      format.js
      format.html
      format.csv {send_data @publishers.to_csv}
      format.xls {send_data @publishers.to_csv(col_sep: "\t")}
    end
  end

  def show
    @books = @publisher.books
      .paginate page: params[:page], per_page: Settings.static_pages.per_page
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = t "admin.publisher.new.success"
      redirect_to admin_publishers_path
    else
      flash[:danger] = t "admin.publisher.new.danger"
      render :new
    end
  end

  def edit
  end

  def update
    if @publisher.update_attributes publisher_params
      flash[:success] = t "admin.publisher.update.success"
      redirect_to admin_publishers_path
    else
      flash[:danger] = t "admin.publisher.update.danger"
      render :edit
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = t "admin.publisher.destroy.success"
    else
      flash[:danger] = t "adnin.publisher.destroy.danger"
    end
    redirect_to :back
  end

  private
  def find_publisher
    @publisher = Publisher.find_by id: params[:id]
    unless @publisher
      flash[:danger] = t "admin.publisher.error.not_found"
      redirect_to root_path
    end
  end

  def publisher_params
    params.require(:publisher).permit :name
  end
end

app/views/admin/publishers/_form.html.erb
<%= form_for [:admin, @publisher] do |f| %>
  <%= render "shared/error_messages", object: @publisher %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/publishers/_navbar.html.erb
<p>
  <%= t "export.name" %>
  <%= link_to t("export.formats.csv"), admin_publishers_path(format: "csv",
    value: params[:value], attribute: params[:attribute]) %> |
  <%= link_to t("export.formats.excel"), admin_publishers_path(format: "xls",
    value: params[:value], attribute: params[:attribute]) %>
</p>

app/views/admin/publishers/_publisher.html.erb
<tr>
  <td class="col-md-2"><%= link_to publisher.name, [:admin, publisher] %></td>
  <td class="col-md-1">
    <%= link_to t("admin.publisher.action.edit"), edit_admin_publisher_path(publisher),
      id: "open-contacts-dialog-btn", class: "btn btn-primary inbox-sf-add-btn tip"%>
    <%= link_to t("admin.publisher.action.delete"), admin_publisher_url(publisher),
      id: "open-contacts-dialog-btn", class: "btn btn-danger inbox-sf-add-btn tip",
      method: :delete, data: {confirm: t("admin.index.confirm")} %>
  </td>
</tr>

app/views/admin/publishers/edit.html.erb
<% provide :title, t("admin.publisher.update.namesite") %>
<% provide :button_text, t("admin.publisher.save") %>
<h1><%= t "admin.book.update.namesite" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/publishers/index.html.erb
<div class="ltt-publishers-index-header">
  <h1 class="col-md-3"><%= t "admin.publisher.all" %></h1>
  <div class="row col-md-9">
    <div class="col-md-6 ltt-publishers-search">
      <%= form_tag admin_publishers_path, method: :get, remote: true do %>
        <%= text_field_tag :value, "", placeholder: t("admin.search"),
          class: "form-control publishers-search-input", value: nil %>
        <%= submit_tag t("admin.search"), class: "btn btn-primary" %>
        <div class="clearfix"></div>
      <% end %>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<div class="row">
<table class="table table-bordered table table-striped">
  <thead>
    <tr>
      <th class="col-md-1"><%= t "admin.publisher.name" %></th>
      <th class="col-md-1"><%= t "admin.publisher.action.title" %></th>
    </tr>
  </thead>
  <tbody class="ltt-publishers-content">
    <%= render @publishers %>
  </tbody>
</table>
<div class="ltt-publishers-navbar pull-left">
  <%= render "navbar" %>
</div>
<div class="ltt-users-navbar pull-right">
  <%= link_to t("admin.publisher.add_publisher"), new_admin_publisher_path,
    id: "open-contacts-dialog-btn", class: "btn btn-primary inbox-sf-add-btn tip" %>
</div>

app/views/admin/publishers/index.js.erb
$('.ltt-publishers-content').html('<%= j render @publishers %>');
$('.ltt-publishers-navbar').html('<%= j render "navbar" %>');

app/views/admin/publishers/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String"><%= t "admin.publisher.name" %></Data></Cell>
          </Data></Cell>
      </Row>
    <% @publishers.each do |publisher| %>
      <Row>
        <Cell><Data ss:Type="String"><%= publisher.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= publisher.body %></Data></Cell>
        <Cell><Data ss:Type="DateTime"><%= publisher.date_of_birth %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/publishers/new.html.erb
<% provide :title, t("admin.publisher.namesite") %>
<% provide :button_text, t("admin.publisher.save") %>
<h1><%= t "admin.publisher.namesite" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/publishers/show.html.erb
<% provide :title, t("publishers.show.title") + @publisher.name %>
<div class="row book-detail">
  <div class="col-sm-12">
    <div class="col-sm-9">
      <h2>
        <%= @publisher.name %>
      </h2>
    </div>
  </div>
  <div class="col-sm-12">
    <h3 class="text-right"><%= t "publishers.show.list_books_of_publisher" %>
      <%= @publisher.name %></h3>
    <hr>
    <div class="col-sm-9 col-sm-offset-3 list-items">
      <% @books.each do |book| %>
        <div class="col-sm-4 item">
          <%= link_to book do %>
            <div class="item-image">
              <%= image_tag "http://allstore-html.real-web.pro/img/catalog-gallery/2/1.jpg" %>
              <div class="item-action">
                <div class="item-box">
                  <p class="item-option text-center">
                  </p>
                  <button class="btn"><%= t "item.add_to_cart" %></button>
                </div>
              </div>
            </div>
          <% end %>
          <i class="item-info">i</i>
          <h4 class="text-center"><%= link_to book.title, "#", title: book.title %></h4>
          <h4 class="text-center"><%= book.price %> <%= t "item.currency" %></h4>
        </div>
      <% end %>
      <hr/>
      <%= will_paginate @books %>
    </div>
  </div>
</div>